
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/data/data/com.termux/files/usr/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Android - 29 - aarch64
...
