add_test([=[DictionaryRecordTest.DefaultConstructor]=]  /data/data/com.termux/files/home/oop_lab1/builder/runTests [==[--gtest_filter=DictionaryRecordTest.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DictionaryRecordTest.DefaultConstructor]=]  PROPERTIES WORKING_DIRECTORY /data/data/com.termux/files/home/oop_lab1/builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DictionaryRecordTest.ParameterizedConstructor]=]  /data/data/com.termux/files/home/oop_lab1/builder/runTests [==[--gtest_filter=DictionaryRecordTest.ParameterizedConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DictionaryRecordTest.ParameterizedConstructor]=]  PROPERTIES WORKING_DIRECTORY /data/data/com.termux/files/home/oop_lab1/builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DictionaryRecordTest.ToString]=]  /data/data/com.termux/files/home/oop_lab1/builder/runTests [==[--gtest_filter=DictionaryRecordTest.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DictionaryRecordTest.ToString]=]  PROPERTIES WORKING_DIRECTORY /data/data/com.termux/files/home/oop_lab1/builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XmlConverterTest.RecordToXml]=]  /data/data/com.termux/files/home/oop_lab1/builder/runTests [==[--gtest_filter=XmlConverterTest.RecordToXml]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XmlConverterTest.RecordToXml]=]  PROPERTIES WORKING_DIRECTORY /data/data/com.termux/files/home/oop_lab1/builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[XmlConverterTest.XmlToRecord]=]  /data/data/com.termux/files/home/oop_lab1/builder/runTests [==[--gtest_filter=XmlConverterTest.XmlToRecord]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[XmlConverterTest.XmlToRecord]=]  PROPERTIES WORKING_DIRECTORY /data/data/com.termux/files/home/oop_lab1/builder SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_TESTS DictionaryRecordTest.DefaultConstructor DictionaryRecordTest.ParameterizedConstructor DictionaryRecordTest.ToString XmlConverterTest.RecordToXml XmlConverterTest.XmlToRecord)
